// Storm gusts: patches of stronger, veered wind carried downwind over the sea.
// Mirrors gust.rs `field` (the CPU evaluates it at the camera for the rain's
// slant; the sea and the spray evaluate it here). GUST_* constants are
// generated by gust.rs `wgsl_source`.

fn gust_hash(x: u32, y: u32, salt: u32) -> f32 {
    var h = (x * 0x8da6b343u) ^ (y * 0xd8163841u) ^ (salt * 0xcb1ab31fu);
    h = (h ^ (h >> 16u)) * 0x7feb352du;
    h = (h ^ (h >> 15u)) * 0x846ca68bu;
    h = h ^ (h >> 16u);
    return f32(h >> 8u) / 16777216.0 * 2.0 - 1.0;
}

// Value noise in -1..1 on a lattice that repeats every `period` cells.
fn gust_value_noise(p: vec2<f32>, period: i32, salt: u32) -> f32 {
    let cell = floor(p);
    let f = p - cell;
    let fade = f * f * f * (f * (f * 6.0 - 15.0) + 10.0);
    let c = vec2<i32>(cell);
    let x0 = u32(((c.x % period) + period) % period);
    let y0 = u32(((c.y % period) + period) % period);
    let x1 = u32((((c.x + 1) % period) + period) % period);
    let y1 = u32((((c.y + 1) % period) + period) % period);
    let bottom = mix(gust_hash(x0, y0, salt), gust_hash(x1, y0, salt), fade.x);
    let top = mix(gust_hash(x0, y1, salt), gust_hash(x1, y1, salt), fade.x);
    return mix(bottom, top, fade.y);
}

// The gust at field coordinate `xi` (cells), -1 (deepest lull) to 1 (strongest
// gust), before the storm's gustiness scales it.
fn gust_field(xi: vec2<f32>) -> f32 {
    let period = i32(GUST_PERIOD_CELLS);
    let broad = gust_value_noise(xi, period, 1u);
    let fine = gust_value_noise(2.0 * xi + vec2<f32>(0.37, 0.61), 2 * period, 2u);
    return clamp((broad + 0.5 * fine) * GUST_FIELD_GAIN, -1.0, 1.0);
}

// Field coordinate of a point `local` metres from the camera in the FFT plane
// (u, v), given the camera's own coordinate `origin` (gust.rs `origin`).
fn gust_coordinate(origin: vec2<f32>, local: vec2<f32>) -> vec2<f32> {
    let along = GUST_WIND_DIRECTION;
    let across = vec2<f32>(-along.y, along.x);
    return origin + vec2<f32>(
        dot(local, along) / GUST_ALONG_METERS,
        dot(local, across) / GUST_ACROSS_METERS,
    );
}

// The wind a gust of `gust` (already scaled by the storm's gustiness) makes of
// the mean wind: faster and veered in a gust, slower and backed in a lull.
fn gust_wind(mean_direction: vec2<f32>, mean_speed: f32, gust: f32) -> vec2<f32> {
    let angle = GUST_VEER_RADIANS * gust;
    let c = cos(angle);
    let s = sin(angle);
    let direction = vec2<f32>(
        c * mean_direction.x - s * mean_direction.y,
        s * mean_direction.x + c * mean_direction.y,
    );
    return direction * (mean_speed * (1.0 + GUST_SPEED_SPREAD * gust));
}
